name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  aarch64_job:
    # The host should always be Linux
    runs-on: ubuntu-20.04
    name: Build on ubuntu-20.04 aarch64
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: uraimo/run-on-arch-action@v2
        name: Build Image
        id: build-image
        with:
          arch: aarch64
          distro: ubuntu20.04
          
          run: | 
            docker build . --file Dockerfile --tag kuma-vault-sidecar:$(date +%s)
