name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        architecture: 'arm64'
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag kuma-vault-sidecar:$(date +%s)
